baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Jeff Stevens'

[params]

[taxonomies]
    category = "categories"
    tag = "tags"

[permalinks]
    posts = "/posts/:slug/"
    projects = "/projects/:slug/"

[markup]
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 3
        ordered = false