baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Jeff Stevens'

[taxonomies]
    category = "categories"
    tag = "tags"

[permalinks]
    posts = "/posts/:slug/"
    projects = "/projects/:slug/"

[markup]
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 3
        ordered = false
    [markup.highlight]
        codeFenses = true
        guessSyntax = false
        lineNos = false
        style = 'monokai'

[params]
    name = "Jeffrey Stevens"
    copyrightYear = 2024