baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[params]
    categories = [
        "Mathematics",
        "Physics",
        "Biotechnology",
        "Technology",
        "R",
        "Misc"
    ]

[taxonomies]
    category = "categories"
    tag = "tags"